#===============================================
# Description: ARMv8 Package
# File name: armv8-package.yml
# Lisence: MIT
# Author: HAIIBO
# code url https://github.com/haiibo
#===============================================

name: pack_opwrt
on:
  workflow_dispatch:
  #schedule:
    #- cron: 30 8 */5 * *
  watch:
    types: started

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  Package:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    name: Package for ${{ matrix.version }}
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android
        sudo -E apt-get -qq update
        sudo -E apt-get -y install $(curl -fsSL is.gd/depends_ubuntu_2204)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"

    - name: Download Armsr(Armvirt) Firmware
      id: download
      run: |
        FIRMWARE_PATH=openwrt/bin/targets/armsr/64
        [ -d $FIRMWARE_PATH ] || mkdir -p $FIRMWARE_PATH
        #FIRMWARE_URL=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" | grep -o "ROOTFS_$VERSION.*rootfs.tar.gz")
        #FIRMWARE_URL=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/download/OpenWrt-NewK" | grep -o "ROOTFS_$VERSION.*rootfs.tar.gz")
        wget -q -P $FIRMWARE_PATH https://productionresultssa4.blob.core.windows.net/actions-results/574b423d-4ef3-4ee4-b0c0-24fb1a35c0d5/workflow-job-run-c7632941-855f-5494-8ed9-7e16b6900374/artifacts/ecad907917b9d14f0ac758540621ccccbb8d56320c5bfc01a5020325b0ec8313.zip?rscd=attachment%3B+filename%3D%2203.15_armsr_armv8.zip%22&se=2025-03-15T09%3A01%3A23Z&sig=KXUayqs3j3hh0t1WScwAy5EDRfLR6W2DS8PQvXUw%2BmE%3D&ske=2025-03-15T17%3A05%3A23Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-03-15T05%3A05%3A23Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-01-05&sp=r&spr=https&sr=b&st=2025-03-15T08%3A51%3A18Z&sv=2025-01-05
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Package Armvirt as OpenWrt
      if: steps.download.outputs.status == 'success'
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*rootfs.tar.gz
        PACKAGE_SOC: s905d
        WHOAMI: very20101
        KERNEL_REPO_URL: https://github.com/ophub/kernel/tree/main/pub/stable
        KERNEL_VERSION_NAME: 5.15.160_6.1.80_6.6.30
        KERNEL_AUTO_LATEST: true
        DISTRIB_REVISION: R${{ env.DATE1 }} by very20101

    - name: Upload OpenWrt To Artifact
      if: env.PACKAGED_STATUS == 'success' && env.UPLOAD_RELEASE != 'true'
      uses: kittaakos/upload-artifact-as-is@master
      with:
        path: ${{ env.PACKAGED_OUTPUTPATH }}

    - name: Upload OpenWrt To Release
      if: env.PACKAGED_STATUS == 'success' && env.UPLOAD_RELEASE == 'true'
      uses: ncipollo/release-action@v1
      with:
        name: R${{ env.DATE }} for ARMv8_Nova${{ env.VERSION }}
        allowUpdates: true
        removeArtifacts: true
        tag: ARMv8_Nova${{ env.VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        body: |
          **This is OpenWrt Firmware for Armsr(Armvirt) 64**
          * ${{ env.EXPLAIN }}
          默认 IP：192.168.1.200 默认密码：password
          安装到 EMMC：系统 → 晶晨宝盒 → 安装 OpenWrt → 选择型号 → 安装
          升级 OpenWrt：系统 → 晶晨宝盒 → 手动上传更新 或者 在线下载更新
          常见问题及注意事项请参考恩山F大➦[最新帖](https://www.right.com.cn/forum/thread-4076037-1-1.html)
          当前使用版本:【编译前的最后一次➦[主源码](https://github.com/openwrt/openwrt)更新记录】
          ${{ env.VERSION_INFO }}
